// pages/index.js
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import SolidTemplate from '@/components/SolidTemplate';
import DetailsComponent from '@/components/details';
import OtherDetailsComponent from '@/components/otherDetails';
import CardsComponent from '@/components/cards/cards';
import FooterComponent from '@/components/footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SolidTemplate />
      <DetailsComponent/>
      <OtherDetailsComponent/>
      <CardsComponent/>
    <FooterComponent/>
    </>
  );
}
